---
- name: Add mesosphere repo
  yum: name={{ mesosphere_yum_repo }} state=present validate_certs=no
  register: yum_res
  retries: 5
  until: yum_res is success  

- name: Downloading and enable the EPEL repository definitions.
  yum: name={{ epel_repo }} state=present

- name: Install os packages
  yum: name={{item}} state=present
  with_items:
    - wget
    - curl
    - unzip
    - libselinux-python 
    - python-setuptools
    - mesos-{{mesos_version}}
    
